### ISSUE TITLE
Plugin not working with TShock v4.5.3

### ISSUE THREAD

**Issue by dringdahl** [Rozen4334/Buildmode#1]
No commands visible in help list. Attempt to use commands gets unknown command response. I was certain to add user permissions first. No errors found in logs.

Also, self reported version when loaded into TShock still says 1.0.0.0.

**Comment by Rozen4334** [comment]
The version is assemblyversion, which is 1.0 by default. The plugin has been tested by me personally on 1.4.2.1,2,3 and works fine. Are you sure you have added the correct permission to the user? The owner role does not have all permissions by default, you will still want to add it manually.
![Capture12](https://user-images.githubusercontent.com/68127614/120700152-96038280-c4b1-11eb-8edd-984abbbeb0a7.PNG)
![Capture13](https://user-images.githubusercontent.com/68127614/120700236-b6cbd800-c4b1-11eb-9335-3c4faee58a1a.PNG)

**Comment by dringdahl** [comment]
Yes, I added the permission. Problem was an extra TShockAPI.dll in main folder. Not sure how it got there. Must have accidentally copied it there somewhere along the line. Anyway, problem is solved. Thank you for your assistance.
